/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Altair.Minimal.Light.Client.Prototype;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
